language: rust
rust:
  - 1.5.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo doc
  - cargo test --verbose;
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench --verbose;
    fi
  - cargo build --verbose --manifest-path=stree_cmd/Cargo.toml
  - cargo build --verbose --manifest-path=suffix_tree/Cargo.toml
  - cargo test --verbose --manifest-path=suffix_tree/Cargo.toml
  - cargo doc --verbose --manifest-path=suffix_tree/Cargo.toml
